[profile.default]
src = 'reference'
reference = 'reference'
out = 'out'
libs = ['lib']
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.default.fuzz]
runs=1000